import { Job } from './types'

const now = Date.now()
const hr = 1000 * 60 * 60

export const MOCK_JOBS: Job[] = [
  {
    id: 'mock-1',
    title: 'Technical Program Manager',
    company: 'Cityblock Health',
    location: 'New York, NY',
    description: 'Drive cross-functional programs across engineering, product, and clinical operations at a Series D health tech company. Partner with engineering, product, and medical teams to deliver complex platform initiatives. Strong communication and stakeholder management skills required. SQL familiarity a plus.',
    salary_min: 130000,
    salary_max: 165000,
    url: 'https://boards.greenhouse.io/cityblockhealth',
    posted_at: new Date(now - hr * 3).toISOString(),
    role_type: 'Technical Program Manager',
    sector: 'HealthTech',
    scores: { technical_fit: 8, comm_fit: 9, growth: 7 },
    is_new: true,
  },
  {
    id: 'mock-2',
    title: 'Solutions Engineer',
    company: 'Ramp',
    location: 'New York, NY',
    description: 'Join our revenue team as a Solutions Engineer, bridging the gap between technical capabilities and customer needs. You will work closely with sales, product, and engineering to win and expand enterprise accounts. Experience with APIs and a background in finance or fintech preferred. Strong presentation and communication skills essential.',
    salary_min: 140000,
    salary_max: 180000,
    url: 'https://ramp.com/careers',
    posted_at: new Date(now - hr * 8).toISOString(),
    role_type: 'Solutions Engineer',
    sector: 'Fintech',
    scores: { technical_fit: 7, comm_fit: 9, growth: 9 },
    is_new: true,
  },
  {
    id: 'mock-3',
    title: 'Associate Product Manager',
    company: 'Ro',
    location: 'New York, NY',
    description: 'Ro is a Series D direct-to-patient healthcare company. As an APM, you will work with cross-functional teams including engineering, design, clinical, and ops to build and ship products that improve patient outcomes. We value speed of learning and ownership over prior PM experience. CS degree or technical background preferred.',
    salary_min: 110000,
    salary_max: 145000,
    url: 'https://ro.co/careers',
    posted_at: new Date(now - hr * 14).toISOString(),
    role_type: 'Associate Product Manager',
    sector: 'HealthTech',
    scores: { technical_fit: 7, comm_fit: 7, growth: 9 },
    is_new: true,
  },
  {
    id: 'mock-4',
    title: 'Customer Success Engineer',
    company: 'Brex',
    location: 'New York, NY',
    description: 'As a CSE at Brex, you will be the primary technical point of contact for our enterprise customers. You will manage complex onboarding projects, coordinate cross-functional teams, and serve as a trusted advisor. Strong relationship management, stakeholder communication, and problem-solving skills required. No coding test.',
    salary_min: 120000,
    salary_max: 155000,
    url: 'https://brex.com/careers',
    posted_at: new Date(now - hr * 22).toISOString(),
    role_type: 'Customer Success Engineer',
    sector: 'Fintech',
    scores: { technical_fit: 7, comm_fit: 9, growth: 8 },
    is_new: true,
  },
  {
    id: 'mock-5',
    title: 'Forward Deployed Engineer',
    company: 'Palantir',
    location: 'New York, NY',
    description: 'Forward Deployed Engineers at Palantir spend time embedded with customers to understand their hardest problems, then work with internal product teams to solve them. You will be part engineer, part consultant, part project manager. Strong communication and the ability to navigate ambiguity are as important as technical skills. Equity included.',
    salary_min: 135000,
    salary_max: 190000,
    url: 'https://palantir.com/careers',
    posted_at: new Date(now - hr * 36).toISOString(),
    role_type: 'Forward Deployed Engineer',
    sector: 'AI',
    scores: { technical_fit: 8, comm_fit: 8, growth: 9 },
    is_new: false,
  },
  {
    id: 'mock-6',
    title: 'Technical Account Manager',
    company: 'Vanta',
    location: 'New York, NY',
    description: 'Own the post-sale technical relationship with Vanta\'s enterprise customers. You will drive adoption, surface expansion opportunities, and serve as the voice of the customer back to product. Strong cross-functional collaboration with engineering, product, and sales is central to this role. Series C, fast-growing, equity available.',
    salary_min: 125000,
    salary_max: 160000,
    url: 'https://vanta.com/careers',
    posted_at: new Date(now - hr * 42).toISOString(),
    role_type: 'Technical Account Manager',
    sector: 'B2B SaaS',
    scores: { technical_fit: 7, comm_fit: 9, growth: 8 },
    is_new: false,
  },
  {
    id: 'mock-7',
    title: 'Implementation Manager',
    company: 'Noom',
    location: 'New York, NY',
    description: 'Lead enterprise onboarding projects for Noom\'s B2B health platform. You will own implementation timelines, coordinate across customer IT, HR, and clinical teams, and work closely with our product and engineering teams to deliver successful launches. Project management and stakeholder communication skills required.',
    salary_min: 110000,
    salary_max: 140000,
    url: 'https://noom.com/careers',
    posted_at: new Date(now - hr * 55).toISOString(),
    role_type: 'Implementation Manager',
    sector: 'HealthTech',
    scores: { technical_fit: 6, comm_fit: 8, growth: 7 },
    is_new: false,
  },
  {
    id: 'mock-8',
    title: 'Product Operations Manager',
    company: 'Rippling',
    location: 'New York, NY',
    description: 'Rippling is a Series F B2B SaaS company unifying HR and IT. As a Product Ops Manager, you will bridge product, engineering, and go-to-market teams — identifying gaps, building processes, and driving cross-functional execution. You are the connective tissue that makes the product org run. Strong analytical and communication skills required.',
    salary_min: 120000,
    salary_max: 155000,
    url: 'https://rippling.com/careers',
    posted_at: new Date(now - hr * 70).toISOString(),
    role_type: 'Product Operations',
    sector: 'B2B SaaS',
    scores: { technical_fit: 6, comm_fit: 8, growth: 7 },
    is_new: false,
  },
  {
    id: 'mock-9',
    title: 'Solutions Consultant',
    company: 'Writer',
    location: 'New York, NY',
    description: 'Writer is an enterprise AI platform for businesses. As a Solutions Consultant, you will lead technical discovery and solution design with enterprise prospects, partnering closely with sales, engineering, and product. AI industry interest is a plus. You thrive in ambiguous situations and are skilled at translating complex technical capabilities into business value.',
    salary_min: 130000,
    salary_max: 170000,
    url: 'https://writer.com/careers',
    posted_at: new Date(now - hr * 80).toISOString(),
    role_type: 'Solutions Consultant',
    sector: 'AI',
    scores: { technical_fit: 7, comm_fit: 9, growth: 9 },
    is_new: false,
  },
  {
    id: 'mock-10',
    title: 'Technical Program Manager',
    company: 'Spring Health',
    location: 'New York, NY',
    description: 'Spring Health is a Series D mental health benefits platform. We are looking for a TPM to lead cross-functional programs across product, engineering, clinical, and ops. You will translate ambiguous strategic goals into concrete execution plans, identify risks and dependencies, and keep teams aligned. Equity and comprehensive benefits included.',
    salary_min: 125000,
    salary_max: 160000,
    url: 'https://springhealth.com/careers',
    posted_at: new Date(now - hr * 95).toISOString(),
    role_type: 'Technical Program Manager',
    sector: 'HealthTech',
    scores: { technical_fit: 8, comm_fit: 8, growth: 8 },
    is_new: false,
  },
  {
    id: 'mock-11',
    title: 'Associate Product Manager',
    company: 'Pave',
    location: 'New York, NY',
    description: 'Pave is a Series B compensation platform used by thousands of companies. As an APM, you will own product areas end-to-end, from writing specs to working with engineering to measuring impact. Strong customer empathy and cross-functional collaboration are essential. We reward ownership and speed over pedigree. Stock options available.',
    salary_min: 105000,
    salary_max: 135000,
    url: 'https://pave.com/careers',
    posted_at: new Date(now - hr * 110).toISOString(),
    role_type: 'Associate Product Manager',
    sector: 'HRTech',
    scores: { technical_fit: 7, comm_fit: 7, growth: 9 },
    is_new: false,
  },
  {
    id: 'mock-12',
    title: 'Solutions Engineer',
    company: 'Cohere Health',
    location: 'New York, NY',
    description: 'Cohere Health uses AI to simplify prior authorization for health plans and providers. As a Solutions Engineer, you will support our sales and customer success teams with technical discovery, demos, and integrations. Deep technical knowledge is less important than your ability to communicate complex concepts clearly and build relationships with healthcare stakeholders.',
    salary_min: 125000,
    salary_max: 158000,
    url: 'https://coherehealth.com/careers',
    posted_at: new Date(now - hr * 130).toISOString(),
    role_type: 'Solutions Engineer',
    sector: 'HealthTech',
    scores: { technical_fit: 7, comm_fit: 9, growth: 8 },
    is_new: false,
  },
]
